application: gu-curating-the-curators
version: 1
runtime: python
api_version: 1


handlers:

################################################################################
# Handlers for the static stuff, img, css, js etc.
################################################################################

- url: /img
  static_dir: img

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /favicon.ico
  static_files: imgs/favicon.ico
  upload: imgs/favicon.ico


################################################################################
# Cron
################################################################################

- url: /admin/cron/fetchStorify
  script: admin/cron/fetchStorify.py
  login: admin


################################################################################
# Main
################################################################################

- url: .*
  script: index.py
